### ISSUE TITLE
Support for writting DBF7 Files

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/javadbf#97]
- [ ] Support for writting DBF7 header
- [ ] Allow field names to be 32 chars length #96 
- [ ] Allow to write timestamp fields #27 #65
- [ ] Support to write long character columns (up to 65534 bytes) #75 #48
